defaults:
  - defaults

USE_TEST: False

MODEL:
  CHECKPOINT: /dd3d/pretrained/depth_pretrained_dla34-y1urdmir-20210422_165446-model_final-remapped.pth

WANDB:
  ENABLED: False

SOLVER:
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 4
